server:
  port: 8060

logging:
  level:
    root: INFO
  org:
    springframework:
      cloud:
        gateway:
          route:
            RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**, /v3/api-docs/authentication
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: authBreaker
#                fallbackUri: forward:/fb/auth/

        - id: twit-service
          uri: lb://twit-service
          predicates:
            - Path=/api/v1/twits/**, /v3/api-docs/twit

        - id: comments-service
          uri: lb://comments-service
          predicates:
            - Path=/api/v1/comments/**, /v3/api-docs/comments
#
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


    discovery:
      enabled: true
    netflix:
      ribbon: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

#SWAGGER UI CONFIGURATION
# swagger-ui custom path http://localhost:8060/swagger-ui.html
